import json

# 创建代码值和可读标签的字典
data = {
    "HC7A": "Electricity",
    "HC7B": "Radio",
    "HC7C": "Television",
    "HC7D": "Non-mobile phone",
    "HC7E": "Fridge",
    "HC7F": "Wardrobe",
    "HC7G": "Table with Chairs",
    "HC7H": "7H",
    "HC7I": "7I",
    # "HC7J": "7J",
    # "HC7K": "7K",
    # "HC7L": "7L",
    # "HC7M": "7M",
    # "HC7N": "7N",
    # "HC7O": "7O",
    "HC8": "Bed",
    "HC9A": "Iron",
    "HC9B": "Hair Dryer",
    "HC9C": "Water Heater",
    "HC9D": "Vacuum cleaner",
    "HC9E": "Freezer",
    "HC9F": "Electric Stove",
    "HC9G": "Washing Machine",
    "HC9H": "Drying Machine",
    # "HC9I": "Dishwasher",
    # "HC9J": "Microwave",
    # "HC9K": "Cable TV/Total TV",
    # "HC9L": "9L",
    # "HC9M": "9M",
    # "HC9N": "9N",
    # "HC9O": "9O",
    # "HC9P": "9P",
    # "HC9Q": "9Q",
    "HC10A": "PC/Laptop",
    "HC10B": "Internet",
    "HC10C": "Air conditioner",
    "HC10D": "Watch",
    "HC10E": "Mobile Phone",
    "HC10F": "Bicycle",
    "HC10G": "Motorcycle or Scooter",
    # "HC10H": "Animal-drawn cart",
    # "HC10I": "Car",
    # "HC10J": "10J",
    # "HC10K": "10K",
    # "HC10L": "10L",
    # "HC10M": "10M",
    # "HC10N": "10N",
    # "HC10O": "10O",
    # "HC10P": "10P",
    # "HC10Q": "10Q",
    # "HC10R": "10R",
    "HC11": "Truck",
    "HC12": "Tractor",
    "HC13": "Owns Dwelling",
    "HC14": "Owns Land",
    "HC15": "Owns animals",
    "HC17": "Bank Account",
    "HC19":"19",
    "wscore":"Wealth Score",
    "HH6": "HH6",
    "id": "id"

}

# 将字典转换为JSON格式的字符串
json_data = json.dumps(data)

# 将JSON字符串写入文件
with open("D:/fanss/try/code/code_to_readable7.json", "w") as file:
    file.write(json_data)

print("JSON文件已创建成功。")



#SerbiaMICS5
    #"HC8A": "Electricity",
    # "HC8B": "Radio",
    # "HC8C": "Television",
    # "HC8D": "Non-mobile phone",
    # "HC8E": "Fridge",
    # "HC8F": "Wardrobe",
    # "HC8G": "Table with Chairs",
    # "HC8H": "Bed",
    # "HC8I": "Iron",
    # "HC8J": "Hair Dryer",
    # "HC8K": "Water Heater",
    # "HC8L": "Vacuum cleaner",
    # "HC8M": "Freezer",
    # "HC8N": "Electric Stove",
    # "HC8O": "Washing Machine",
    # "HC8P": "Drying Machine",
    # "HC8Q": "Dishwasher",
    # "HC8R": "Microwave",
    # "HC8S": "Cable TV/Total TV",
    # "HC8T": "PC/Laptop",
    # "HC8U": "Internet",
    # "HC8V": "Air conditioner",
    # "HC9A": "Watch",
    # "HC9B": "Mobile Phone",
    # "HC9C": "Bicycle",
    # "HC9D": "Motorcycle or Scooter",
    # "HC9E": "Animal-drawn cart",
    # "HC9I": "Car",
    # "HC9J": "Truck",
    # "HC9K": "Tractor",
    # "HC10": "Owns Dwelling",
    # "HC11": "Owns Land",
    # "HC13": "Owns animals",
    # "HC15": "Bank Account",
    # "wscore":"Wealth Score",
    # "id": "id",
    # "HH6": "area"